name: dependencies
description: A new Flutter project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  internet_connection_checker_plus: ^2.5.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  dartz: ^0.10.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
