name: dependencies
description: A new Flutter project.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  internet_connection_checker_plus: ^2.5.2
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  rxdart: ^0.28.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.4.1
  lottie: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
