name: core
description: A new Flutter project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  dependencies:
    path: ../dependencies




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

